export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const GET_INGREDIENTS = 'GET_INGREDIENTS';

export const FETCH_ORDERS = 'FETCH_ORDERS';
export const SPINNER_FLAG_START = 'SPINNER_FLAG_START'
export const REDIRECT_FLAG = 'REDIRECT_FLAG';
export const FETCH_ORDERS_ERROR_HANDLING = 'FETCH_ORDERS_ERROR_HANDLING';
export const CHECKOUT_FLAG = 'CHECKOUT_FLAG';


export const GET_ORDER_SUCCESS = 'GET_ORDER_SUCCESS'
export const GET_ORDER_FAILED = 'GET_ORDER_FAILED'

export const AUTH_INIT = 'AUTH_INIT'
export const AUTH_SUCCESS= 'AUTH_SUCCESS'
export const AUTH_FAIL= 'AUTH_FAIL'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'


